on:
  push:
    branches:
      - "main"
  pull_request:

name: test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
      - run: go version
